### ISSUE TITLE
Fix bug where minWeight can be greater than maxWeight

### ISSUE THREAD

**Issue by mantono** [mantono/GymData#34]
Exception in thread "main" java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 114.9 kg is less than minimum 199.8 kg.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:784)
	at com.mantono.gym.WeightComputer.computeWeight(WeightComputer.kt:43)
	at com.mantono.gym.WeightComputer.getWeight(WeightComputer.kt:19)
	at com.mantono.gym.Exercise.getWeight(Exercise.kt:19)
	at com.mantono.gym.Workout.print(Workout.kt:103)
	at Main.main(Main.java:35)

**Comment by mantono** [comment]
Fixed in e70c6d3109da92afa2
